// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using petshop_API.Data;

#nullable disable

namespace petshop_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240613221346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("petshop_API.Models.Petshop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double>("LargeDogWeekdayPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("LargeDogWeekendPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SmallDogWeekdayPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("SmallDogWeekendPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Petshop");
                });
#pragma warning restore 612, 618
        }
    }
}
